apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: confluence
  name: confluence
spec:
  containers:
  - image: atlassian/confluence:8.5.6
    name: confluence
    resources: {}
  - image: postgres:latest
    name: confluence-db
    env:
      - name: TZ
        value: Asia/Seoul
      - name: POSTGRES_PASSWORD
        value: postgres1234
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
