apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 10.252.0.214
      share: /utest/static
      subdir: test-volume
    volumeHandle: 10.252.0.214#utest#static#test-volume##
  mountOptions:
  - hard
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem

