apiVersion: v1
kind: Secret
metadata:
  name: nginx-config
stringData:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-html
stringData:
  index.html: "nginx html index page"
  50x.html: "50x error"

---
apiVersion: v1
kind: Secret
metadata:
  name: envtest
stringData:
  ENV01: testvalue
  EVALUE: evalue test

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: secret-test
  name: secret-test
spec:
  containers:
  - image: nginx:latest
    name: nginx
    env:
      - name: ENV01
        valueFrom:
          secretKeyRef:
            name: envtest
            key: ENV01
      - name: ENV02
        valueFrom:
          secretKeyRef:
            name: envtest
            key: EVALUE
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html-secret
      - mountPath: /etc/nginx/conf.d/default.conf
        name: config-secret
        subPath: default.conf

  volumes:
    - name: html-secret
      secret:
        secretName: nginx-html
    - name: config-secret
      secret:
        secretName: nginx-config

